image:
  name: opencontent-common-utils
  tag: faf15a2-amd64
  pullPolicy: IfNotPresent
  pullSecret: ""

global:
  image:
    repository: ""

rbac:
  serviceAccountName: "ibm-sch-secret-gen"

jobPreinstallWeight: -1
jobPreinstallDeletePolicy: "hook-succeeded"
jobPostdeleteDeletePolicy: "hook-succeeded"
jobPostDeleteWeight: 2
